### ISSUE TITLE
Margins when exporting SVG

### ISSUE THREAD

**Issue by diomidov** [edemaine/cocreate#105]

**Comment by edemaine** [comment]
Could you explain why you'd like margins? Just visually nicer, or were you seeing actual clipping in the current setup?

A natural choice for margin at this point would be one grid square. Maybe only when the grid is on?

**Comment by diomidov** [comment]
I wanted margins because marginless images look ugly on Coauthor with dark theme. Now that I think about it, maybe it makes more sense to add some `padding` on Coauthor side.
