### ISSUE TITLE
Components not working- copy url, help documentation-go to github repository

### ISSUE THREAD

**Issue by jkodish** [edemaine/cocreate#116]
I've installed this on my own linux box. When clicking on the user guide, go to github, or copy url button, nothing happens. 
The url doesn't get copied onto the clipboard, the guide does not open and the link to github doesn't open either.
This has been tested in chrome and firefox.
I followed the directions to set up a test server.

**Comment by edemaine** [comment]
Is there an error message in the JavaScript console? Did you run `npm install`?

**Comment by jkodish** [comment]
For the clipboard:
Uncaught TypeError: can't access property "writeText", navigator.clipboard is undefined
    once main.coffee:918
    selectTool main.coffee:2039
    click main.coffee:2002
For Github access:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3000/__meteor__/dynamic-import/fetch. (Reason: CORS request did not succeed).
Same for the user guide
Odd though, all this works on the https://cocreate.csail.mit.edu site, so I think it’s likely I’ve set something up wrong. Just not sure what it is.
Thanks!
Sent from Mail for Windows 10

**Comment by edemaine** [comment]
Are you accessing the site as `http://localhost:3000`? Anything else would likely cause the CORS error you're getting.

**Comment by jkodish** [comment]
Ah ok. Nope doing it across the network.Not sure how to get it working from a remote ip. There's stuff about editing a mups file but I'm not sure where to edit.(Also to run it on https)Thank you for helping on thisSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Erik Demaine <notifications@github.com> Date: 2020-10-09  6:31 a.m.  (GMT-07:00) To: edemaine/cocreate <cocreate@noreply.github.com> Cc: jkodish <jkodish@shaw.ca>, Author <author@noreply.github.com> Subject: Re: [edemaine/cocreate] Components not working- copy url, help documentation-go to github repository (#116) 
Are you accessing the site as http://localhost:3000? Anything else would likely cause the CORS error you're getting.

**Comment by edemaine** [comment]
To keep running as a test server, you need to set the `ROOT_URL` environment variable to the intended address of your server.  Something like this:
```
ROOT_URL=http://my.server.name:3000/ meteor
```

But to get https support, you need a real deployment, not test server. The [public server instructions](https://github.com/edemaine/cocreate/blob/master/INSTALL.md#public-server) say which `mup.js` file to edit.  You probably want to read about `meteor-up` as well, which is linked from that documentation.

**Comment by jkodish** [comment]
For the test server would this just be set on the command line or in one of the files?Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Erik Demaine <notifications@github.com> Date: 2020-10-09  9:38 a.m.  (GMT-07:00) To: edemaine/cocreate <cocreate@noreply.github.com> Cc: jkodish <jkodish@shaw.ca>, Author <author@noreply.github.com> Subject: Re: [edemaine/cocreate] Components not working- copy url, help documentation-go to github repository (#116) 
To keep running as a test server, you need to set the ROOT_URL environment variable to the intended address of your server.  Something like this:
ROOT_URL=http://my.server.name:3000/ meteor

But to get https support, you need a real deployment, not test server. The public server instructions say which mup.js file to edit.  You probably want to read about meteor-up as well, which is linked from that documentation.

**Comment by edemaine** [comment]
`ROOT_URL=http://my.server.name:3000/ meteor` is a command you would enter on the command line (instead of `meteor`).

**Comment by jkodish** [comment]
Thank you that worked. Will test the rest later. If you want to clear all the old boards out of the database how do you do that?Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Erik Demaine <notifications@github.com> Date: 2020-10-09  1:46 p.m.  (GMT-07:00) To: edemaine/cocreate <cocreate@noreply.github.com> Cc: jkodish <jkodish@shaw.ca>, Author <author@noreply.github.com> Subject: Re: [edemaine/cocreate] Components not working- copy url, help documentation-go to github repository (#116) 
ROOT_URL=http://my.server.name:3000/ meteor is a command you would enter on the command line (instead of meteor).

**Comment by edemaine** [comment]
To clear the entire database of the test server, you can use `meteor reset`.

**Comment by jkodish** [comment]
Thanks, that worked.

I’m trying to set up a public server.  I’ve generated an ssh key with ssh-keygen


module.exports = {
  servers: {
    one: {
      host: 'xxxxx.thirring.org',
      username: '<account it’s running under>',
      pem: "/home/<account it’s running under>/.ssh/id_rsa"
      // pem:
      // password:
      // or leave blank for authenticate from ssh-agent
    }
  },

When I run mup setup, it fails with this underneath the “Setup Docker”
Not sure what I’m doing wrong here.
Thanks

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: All configured authentication methods failed
    at doNextAuth (/usr/local/lib/node_modules/mup/node_modules/ssh2/lib/client.js:413:17) at tryNextAuth (/usr/local/lib/node_modules/mup/node_modules/ssh2/lib/client.js:484:5)
    at SSH2Stream.onUSERAUTH_FAILURE (/usr/local/lib/node_modules/mup/node_modules/ssh2/lib/client.js:597:5)
    at emitTwo (events.js:126:13)
    at SSH2Stream.emit (events.js:214:7)
    at parsePacket (/usr/local/lib/node_modules/mup/node_modules/ssh2-streams/lib/ssh.js:3682:10)
    at SSH2Stream._transform (/usr/local/lib/node_modules/mup/node_modules/ssh2-streams/lib/ssh.js:701:13)
    at SSH2Stream.Transform._read (_stream_transform.js:186:10)
    at SSH2Stream._read (/usr/local/lib/node_modules/mup/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at SSH2Stream.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)




Sent from Mail for Windows 10

**Comment by edemaine** [comment]
This is an issue with mup, not Coauthor, so you might post there.

If I had to guess, though, it's that you didn't add your public key to `.ssh/authorized_keys` on the public server.

**Comment by jkodish** [comment]
Thanks for the help. At this point I've made it to the mup deploy stage but this fails with docker file parse error  Arg requires exactly one argument. I have no idea how to fix this.
Will just run as a test server internally
