### ISSUE TITLE
Erase Whiteboard

### ISSUE THREAD

**Issue by Martybay** [edemaine/cocreate#120]
I use your whiteboard in the Gather space I have created. It would be really helpful if I could click a button and erase the whiteboard while working with a student. I don't want the answer to the problem showing when I work with the next student. Also, it would be great to be able to delete pages. Since I can't erase the page quickly while working with a student, I create a new page. Now I have a ton of pages and no way to get rid of them. Also, it always starts me at the first page. All that to say, it would be really great to either easily erase the whiteboard and/or easily delete pages.

**Comment by edemaine** [comment]
It sounds like the right way to deal with this is page deletion (already listed in #18, so you might want to follow that issue). This is definitely high on my priority list, but I can't say when it will be implemented.

**Comment by edemaine** [comment]
By the way, meanwhile there is a quick way to erase an entire page: use the select tool to drag a big rectangle over the entire page (after zooming out appropriately), and then press the delete key on your keyboard. Hopefully this helps.
