### ISSUE TITLE
Drawing pen does not write where the nib is

### ISSUE THREAD

**Issue by daveisagit** [edemaine/cocreate#129]
The free hand drawing tools writes 5mm above where the pointer / pen nib is

**Comment by edemaine** [comment]
What browser and version are you using? If Chrome, can you try updating? (A recent update fixed this bug in Chrome.) 

A workaround is to switch to the crosshair cursor (a toggle on the left, roughly in the middle). Normally this turns on automatically if you're using a version of Chrome that has this bug, so I'm surprised that you're seeing this.

**Comment by daveisagit** [comment]
thanks @edemaine upgrading Chrome fixed the issue

**Comment by daveisagit** [comment]
thanks @edemaine upgrading Chrome fixed the issue
