### ISSUE TITLE
Zooming and pinch to zoom

### ISSUE THREAD

**Issue by edemaine** [edemaine/cocreate#13]
- [x] Zoom in/out buttons
- [x] Scroll wheel should zoom -- or perhaps scrolling should pan, and ctrl-scrolling should zoom?  (This is how browsers work, and [zoom gestures on trackpads send exactly this WheelEvent](https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent)... except in Safari.)
- [x] [Pinch to zoom](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events/Pinch_zoom_gestures) should always work in pan mode
- [x] Pinch to zoom when touch drawing is disabled
- [ ] We should have a toggle between
     * multiple pens drawing at once
     * pinch to zoom and two-finger dragging
- [x] Button to return to original 1x zoom
- [x] Button to fit contents to screen (with some buffer)

**Comment by edemaine** [comment]
Basic zoom functionality (via buttons) now live!

**Comment by diomidov** [comment]
Maybe cocreate should disable browser's default `Ctrl`+`+`/`-` and `Ctrl`+mouse wheel behavior?
