### ISSUE TITLE
Feature request: Clear entire whiteboard (and possibly history)

### ISSUE THREAD

**Issue by dpl** [edemaine/cocreate#132]
Hi, thanks for cocreate ! It would be great to be able to clear the entire whiteboard quickly, and possibly its history as well.

**Comment by edemaine** [comment]
On Chrome, you can select all objects fairly quickly using rectangular select, then using the <kbd>Delete</kbd> key to delete everything.  It might be nice to have a select-all feature like <kbd>Ctrl-A</kbd> to make this a little easier.

If you want to delete history, you should probably run your own server. Until we have user accounts (#4) to lock down permissions, I view deleting history as too dangerous an operation to be made available to the client.

But you may be looking for page deletion/archiving, which is part of #18.

It would be helpful to know, among these options, which would be attractive solutions to you, so I can prioritize development. Page archiving is currently near the top of my list.
