### ISSUE TITLE
Clear whole page/whiteboard and/or delete page

### ISSUE THREAD

**Issue by Hmmmbeee** [edemaine/cocreate#141]
I'm using Cocreate whiteboards in Gather.town and I don't have a way to quickly erase all the whiteboards before a new group of students come in. If there was a way to clear whole pages, or all pages, or just delete pages, that would be hugely appreciated, thanks.

**Comment by bernadettemchugh** [comment]
yes, agreed - this would be key for us as a math institute with several whiteboards throughout our space - having to erase each one individually is not ideal

**Comment by edemaine** [comment]
@Hmmmbeee @bernadettemchugh Please see the discussion on #132 and add to the discussion there if you have further thoughts. Thanks!
