### ISSUE TITLE
SVG/PNG/JPG embedding

### ISSUE THREAD

**Issue by edemaine** [edemaine/cocreate#144]
As a simpler first step toward actual file upload (#22), I'm planning to add external image embedding from `https` sources, such as Imgur or Coauthor.
- [x] Dragging images onto the canvas
- [x] Dragging link to image onto the canvas
- [x] Pasting link to image (when drag is inconvenient)
- [x] In all cases, check URL for loading error (in particular CORS) before adding; maybe automatically apply CORS Anywhere as a second try. Ditto for whether to send credentials. Should also check that the data is an actual image...
  - [x] Document how to set up CORS Anywhere proxy
- [x] Image objects and rendering
  - [x] Highlight needs to behave differently for image objects (current technique is invisible); or should images have borders?
  - [x] When rendering, check for loading error and display something else
- [x] Mode to bring up text entry on bottom where you can type URL and see preview of image (maybe just automatically always trying to load image, and creating image object upon success, editing thereafter)
  - [x] Also edit existing URLs (in case image moved), updating only when URL is successful
  - [ ] Checkboxes for credentials and proxy?
  - [x] Reload button? (in particular when image previously errored out) Currently this can be done by just pressing Enter.
- [x] Drag default location according to last `dragover` event
- [x] Paste default location: middle of screen?
- [x] Download SVG should inline images in base64
- [ ] Copy to clipboard should maybe copy image directly when just image is selected
- [x] Documentation

**Comment by edemaine** [comment]
This is done and deployed! Please let me know if you have any issues with it (probably in a new issue).

**Comment by diomidov** [comment]
Dragging images from another comingle tab doesn't work (tested in Firefox and Chromium).
