### ISSUE TITLE
multiline text boxes

### ISSUE THREAD

**Issue by sdspikes** [edemaine/cocreate#152]
I'm considering using this tool (within a gather.town space) for whiteboarding for a data structures and algorithms course (e.g. to draw pointer diagrams + write pseudo-code/code), and it would be much more useful/useable for that purpose if I could have multiline text blocks.  I tried it out by myself just now with separate text boxes per line and it was a pretty bad experience.  

Even better would be the ability to embed something like repl.it for code editing + evaluation, but just being able to type multi-line text would be a big improvement.

Apologies if this is already possible and I just missed it!

**Comment by edemaine** [comment]
@sdspikes Text boxes already support multiple lines. Just press enter to start a new line. (Or what server are you using? Perhaps it's running an old version?)

\`\`\` isn't currently supported by the very simple Markdown parser, but \` does work across the multiple lines, it seems.  Fine as long as your code doesn't have any \`s in it. 🙂
