### ISSUE TITLE
Lag with iPads

### ISSUE THREAD

**Issue by agrebe** [edemaine/cocreate#158]
Both we and some students have noticed that there can be a substantial lag on iPads, that makes it difficult to write on them in real time. In particular, curved lines are hard to draw unless one goes very slowly, and operations take longer in general. These problems arise on both Safari and Chrome on an iPad. In contrast, on a USB tablet, the software works great and is very fast. It is similarly fast when connecting an iPad to a Mac using Sidecar; only when using the iPad as a standalone device is there substantial lag.  Is this a known issue and is there a way to solve this problem, e.g. some setting on the iPad browser that needs changing?
Thanks!  Anthony Grebe & Prof. Iain Stewart

**Comment by edemaine** [comment]
I've heard some reports of this on older iPads, but it's difficult for me to track down (especially as I don't own an iPad, old or new). I hear that Cocreate works well/better on newer iPads.

One query: which version of iOS are you/they using? Upgrade to the latest if possible, and let me know whether that helps. It would also be helpful to know which models of iPads exhibit the problem. (Perhaps I can get one to test.)

In general, Cocreate doesn't run very well on Safari (sadly Safari is old and not well maintained), and on iOS devices you can't run anything but Safari. (Chrome exists, but it's using the Safari engine internally.) So there aren't a lot of alternatives on an iPad, and I'm not sure what to fix it on the Cocreate side (if it's even possible).

**Comment by agrebe** [comment]
Thank you for your quick reply, and sorry that it took me a while to get back to you.
- One person told me that they were using iOS 14.3, which I think is close to the latest one.
- One person told me that they were using an iPad from 2017, although I don't know which version of iOS this is running.
- One person was a student who I think is using an iPad loaned from MIT through the student loaner program.  I'm not exactly sure what model these are, but I'd assume that these were purchased recently by MIT and would be new models.
That's unfortunate that iPads are restricted to the Safari engine even when running Chrome.

**Comment by eltoroit** [comment]
In case this helps... I am also running on an iPad and the performance is not as good as other whiteboard tools I have been testing (for example: https://wbo.ophir.dev/boards/etertrt).

The performance is horrible slow when drawing a continuously long freehand line. I am using chrome on an iPad Pro (11-inch) with iPadOS 14.4.1

**Comment by psvenk** [comment]
I'm not sure if this is the same issue as what was reported here, but there is a WebKit bug which causes some strokes not to be registered; disabling the "Scribble" feature works around this bug. More info: https://github.com/H-M-H/Weylus/issues/44

**Comment by edemaine** [comment]
I acquired an iPad for testing, and it seems that the issue was indeed the Scribble feature.  I found [this simple workaround](https://mikepk.com/2020/10/iOS-safari-scribble-bug/) and it seems to have fixed everything (even with Scribble enabled).  So Cocreate seems to work well on iPads now (at least, on the iPad Air 4 I'm testing).
