### ISSUE TITLE
Option to resize images

### ISSUE THREAD

**Issue by psvenk** [edemaine/cocreate#162]
Currently, it seems that it is necessary to manually resize images before/during uploading; it would be nice if Cocreate had a way to resize images (similar to how text can be resized and the pen can be made thicker or thinner).

**Comment by edemaine** [comment]
Agreed, and this is a high priority. It's part of issue #17. If you have further ideas on what the UI should look like, feel free to post them there. Unfortunately, I don't think it makes sense to have a set of buttons like text size and pen thickness, as there are no "natural" values for scale.
