### ISSUE TITLE
Horizontal/vertical lines with Shift

### ISSUE THREAD

**Issue by diomidov** [edemaine/cocreate#187]
I think it used to be possible to draw horizontal/vertical lines while holding Shift. But now it only draws diagonal lines unless you are pixel-perfect.

**Comment by diomidov** [comment]
Now you can't make diagonal lines with Shift. I thought it's supposed to snap to the nearest multiple of 45?

**Comment by edemaine** [comment]
That's not how it used to work.

<kbd>Shift</kbd> could allow 45 degrees...  Admittedly, Illustrator does this.  (I somehow thought it only did orthogonal.)

Ideally you could specify the n to divide 360 by. This is #123, so maybe should discuss there.
