### ISSUE TITLE
Ghost objects

### ISSUE THREAD

**Issue by diomidov** [edemaine/cocreate#190]
Sometimes when you deselect text, the selection shadow remains. It stays there even if you delete, move, or edit the original text object. Switching to a different page and back fixes it.

![image](https://user-images.githubusercontent.com/22151995/122662391-8f873300-d160-11eb-9c20-ad342a76f51d.png) ![image](https://user-images.githubusercontent.com/22151995/122662371-6e264700-d160-11eb-8d9a-814dae46751d.png)

I have only seen this happen twice, and I haven't been able to reproduce it :(

**Comment by diomidov** [comment]
I have managed to reproduce it a few times, but I still can't do it consistently:
![image](https://user-images.githubusercontent.com/22151995/122684958-a4061280-d1d6-11eb-81f1-4bca56964951.png)

**Comment by edemaine** [comment]
I've seen this too, but it's tricky to reproduce which makes it tricky to track down. In your reproductions, have you been using multiple browser windows on the same board, or were you able to reproduce it in a single tab?

**Comment by diomidov** [comment]
I've only used single tab.

Turns out it has nothing to do with text:
![image](https://user-images.githubusercontent.com/22151995/122694691-34ab1580-d20c-11eb-8d62-0492bea98fee.png)

**Comment by edemaine** [comment]
I found a reliable way to reproduce this:
1. Create a text object and leave it selected and hovered
2. Go to another tab without moving the mouse
3. Delete the text object
4. Original tab has ghost(s)

I also am now deploying a fix to this problem.  Let me know if you see ghosts again; if not, this may finally be fixed.
