### ISSUE TITLE
Should be able to choose color to fill shapes without a keyboard.

### ISSUE THREAD

**Issue by flooie** [edemaine/cocreate#195]
I would like to be able to select a fill color for shapes without a keyboard.

I would suggest that a 2 second long press on the color of choice would be a simple way to select a fill option without much mess (although somewhat undiscoverable.)

**Comment by edemaine** [comment]
I agree.  #96 was one proposal for this.  Do you agree that would be nice/sufficient?

I could see long-press bringing up a menu, offering stroke or fill color maybe?

**Comment by flooie** [comment]
I see this may related or duplicative to #96 

closing to shift there.
