### ISSUE TITLE
LaTeX offset in Firefox

### ISSUE THREAD

**Issue by edemaine** [edemaine/cocreate#199]
Math seems to render bottom-aligned with the baseline, instead of matching baselines:

![image](https://user-images.githubusercontent.com/2218736/158696847-c2fa408d-06ec-41e4-95c5-9c48845de30b.png)

This can do weird things when combined with the selection cursor: if you have text like this, zoom out a bunch via Cocreate zoom, and edit the text, the offset can be further exaggerated, I think because the math is getting placed relative to the top of the bounding box?

![image](https://user-images.githubusercontent.com/2218736/158697021-511e1caf-39a7-4120-9b2e-c5f107f3819b.png)

**Comment by diomidov** [comment]
You also get an exaggerated offset if you load the page while zoomed out or duplicate a text object while zoomed out.

**Comment by edemaine** [comment]
I did some investigation today and isolated to [this Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1783729).

I might be able to work around this bug by turning off the transform for the duration of measurement...
