### ISSUE TITLE
Instructions to run locally

### ISSUE THREAD

**Issue by xennygrimmato** [edemaine/cocreate#2]
I want to play around with the app. What libraries do I need to install on my machine and what commands do I need to execute to get this up and running?

**Comment by edemaine** [comment]
This should work:

```
npm install
meteor
```

**Comment by edemaine** [comment]
P.S. You'll also need to install Meteor, as described in [this document](https://github.com/edemaine/coauthor/blob/master/INSTALL.md).

**Comment by xennygrimmato** [comment]
Thanks! It works on my machine 🙂
