### ISSUE TITLE
No way to make division symbol in LaTeX?

### ISSUE THREAD

**Issue by mjxbenet** [edemaine/cocreate#208]
It looks like Cocreate uses the physics package, rather than math, so \div results in the following triangle dot: 
![119d1831-71cf-40a4-a4e9-20c832142d3c](https://user-images.githubusercontent.com/69053576/171548414-f48a4ec0-e658-482a-9e87-0686343e1728.jpg)

Is there any way to get the division symbol? I'm not sure what a fix would look like - is there a LaTeX library on the backend that can be updated with something like \divisionsymbol or \olddiv?

**Comment by edemaine** [comment]
Thanks for the report. Preventing the `\div` symbol seems pretty terrible, so I think I'll just remove the physics package.

**Comment by edemaine** [comment]
Should be fixed now!

![image](https://user-images.githubusercontent.com/2218736/171749283-439dfeca-ccdc-404e-8f9d-d174cbfa7933.png)
