### ISSUE TITLE
Write README

### ISSUE THREAD

**Issue by edemaine** [edemaine/cocreate#26]
- [ ] Main goals
- [x] Current features
- [x] Highlight what's special
- [x] Planned features
- [x] Screenshot

**Comment by adqm** [comment]
Along these lines, maybe also a short end-user-facing documentation page that is readily accessible from within cocreate (i.e., that doesn't require visiting an external site).  I'm not sure how necessary that is, given that the tooltips exist, but it might still not be a bad idea.

**Comment by edemaine** [comment]
There's now a [README with highlights](https://github.com/edemaine/cocreate/#cocreate) and, as @adqm suggested, a [User Guide](https://github.com/edemaine/cocreate/blob/master/doc/README.md).  Hopefully this makes it easy for people to learn Cocreate!
