### ISSUE TITLE
"Copy link to current whiteboard" button

### ISSUE THREAD

**Issue by PMKielstra** [edemaine/cocreate#40]
While copying the link to a whiteboard can be done by the URL bar, having a button would make it easier for some users to remember that this was the correct way to share a whiteboard.  Perhaps it might also be fun to have an "Email link to whiteboard" button which the backend handles via an SMTP server?

**Comment by edemaine** [comment]
I like the idea of the "copy link to clipboard" button.  Less sure that email is useful -- usually I want to share a whiteboard *right now* and email is usually too slow for that...  Once there are user accounts (#4), I could see inviting them that way, though.
