### ISSUE TITLE
Behavior When Visiting a Nonexistent Room

### ISSUE THREAD

**Issue by adqm** [edemaine/cocreate#45]
As of right now, if I try to visit a room that doesn't exist, e.g. , I see a blank page and lots of errors in the dev console whenever I, for example, move the cursor, try to draw, etc.

I'm not familiar enough with Meteor/cocreate yet to attempt a change myself, but it feels like one of two things should happen in this case:

1. a new room could be created with the given id, or
2. an error page could be shown, maybe with a link to `/` so that making a new room is easy

I might lean toward showing an error page, since this likely comes about as a result of missing a character when copy/pasting a link or something.  But maybe the behavior could also be toggled via `settings.json`?

**Comment by edemaine** [comment]
Agreed. I am worried about Behavior 1 because it would allow people to make insecure room names that are easy to guess, and especially without user authentication, this is risky (the equivalent of Zoom bombing).  But Behavior 2 is a good idea and shouldn't be hard to implement.  I'll work on it.
