### ISSUE TITLE
click-and-drag for rectangular select

### ISSUE THREAD

**Issue by adqm** [edemaine/cocreate#54]
it would be great if one could click and drag to select all objects in a rectangular region, rather than having to click on individual objects directly

one could imagine: if the selection tool is active and the click is on an object, keep the existing behavior.  if not, start a rectangular select (make the selection official when the click is released).  in either case, holding the shift button should add objects to the selection rather than resetting it.

**Comment by edemaine** [comment]
Yep, that's what I had in mind for #17 (rectangular select). High on my list...

**Comment by adqm** [comment]
Ah, OK, great!  I hadn't noticed that this was already on the roadmap.

**Comment by edemaine** [comment]
Rectangular select is complete! (and will be live in a few minutes)

Let me know if you encounter any issues with it.
