### ISSUE TITLE
handling short windows

### ISSUE THREAD

**Issue by adqm** [edemaine/cocreate#55]
right now, if the window height is small enough that not all of the tool icons can fit vertically, we get a strange artifact off to the right of the menu, in addition to not displaying all of the tools:

![image](https://user-images.githubusercontent.com/549404/85499481-b04d9480-b5af-11ea-97dc-bf67e01eac5d.png)

i'm not quite sure where that artifact is coming from.  but additioanally, maybe it makes sense, when the window becomes short enough, to collapse some of the tool icons into a single button that pops up those options when clicked?

**Comment by edemaine** [comment]
Thanks for reporting this! I must have introduced this bug when adding the fancy tool tips, which occupy that space to the right of the buttons. The intended behavior (for now) is for the scrollbar to appear next to the tools.

We could also consider grouping related buttons, or using two columns of buttons, or maybe allowing the user to scale the buttons... But first I should fix the intended behavior.
