### ISSUE TITLE
double click in text mode results in a broken state

### ISSUE THREAD

**Issue by npfoss** [edemaine/cocreate#69]
I've noticed that sometimes when in text mode I get stuck in a state where I can't type text or change the mode on the left, and I have to refresh the page. Here's the error associated with clicking on the canvas or another mode button:
![image](https://user-images.githubusercontent.com/10506482/90279421-2eebe300-de37-11ea-8241-e55ea402dfbf.png)

I can reliably reproduce this by double clicking really fast on the canvas while in text mode, but I think there are other ways to cause it too because it was happening before without double clicks (just not reliably).

Also, thanks so much for making this tool :) it's invaluable in a time like this...

**Comment by edemaine** [comment]
Thanks for spotting this!  I was able to track down and (I believe) fix the bug.  "Conveniently", I encountered the same bug (even on single click) when tracking down some bugs on iOS.

Fixed version is deployed. Let me know if you see any other issues!
